import type { RehabMenu, Patient, Staff } from "@/types";

export const rehabMenus: RehabMenu[] = [
  {
    id: "menu-001",
    name: "脳卒中急性期 基本メニュー",
    diseaseType: "stroke",
    phase: "acute",
    totalDurationMinutes: 30,
    isActive: true,
    createdAt: "2024-01-10",
    updatedAt: "2024-03-15",
    exercises: [
      {
        id: "ex-001",
        name: "関節可動域訓練（上肢）",
        description: "肩・肘・手首の他動的関節可動域訓練",
        category: "stretching",
        durationMinutes: 10,
        precautions: ["痛みがある場合は中止", "無理な伸張を避ける"],
      },
      {
        id: "ex-002",
        name: "体位変換訓練",
        description: "ベッド上での寝返り・起き上がり練習",
        category: "daily_activity",
        durationMinutes: 10,
        precautions: ["血圧変動に注意", "めまいがある場合は中止"],
      },
      {
        id: "ex-003",
        name: "座位バランス訓練",
        description: "端座位でのバランス保持練習",
        category: "balance",
        durationMinutes: 10,
        precautions: ["転倒に注意", "必ずスタッフが付き添う"],
      },
    ],
  },
  {
    id: "menu-002",
    name: "脳卒中回復期 歩行メニュー",
    diseaseType: "stroke",
    phase: "recovery",
    totalDurationMinutes: 60,
    isActive: true,
    createdAt: "2024-01-15",
    updatedAt: "2024-03-20",
    exercises: [
      {
        id: "ex-004",
        name: "平行棒歩行訓練",
        description: "平行棒を使用した歩行練習",
        category: "daily_activity",
        durationMinutes: 20,
        precautions: ["装具の装着確認", "介助者の配置"],
      },
      {
        id: "ex-005",
        name: "下肢筋力強化（SLR）",
        description: "仰臥位での下肢直脚挙上運動",
        category: "strength",
        durationMinutes: 15,
        sets: 3,
        reps: 10,
      },
      {
        id: "ex-006",
        name: "バランスボード訓練",
        description: "立位バランスの改善",
        category: "balance",
        durationMinutes: 15,
        precautions: ["転倒防止のため必ず補助"],
      },
      {
        id: "ex-007",
        name: "ADL練習（更衣）",
        description: "片麻痺患者の更衣動作練習",
        category: "daily_activity",
        durationMinutes: 10,
      },
    ],
  },
  {
    id: "menu-003",
    name: "整形外科回復期 TKA後メニュー",
    diseaseType: "orthopedic",
    phase: "recovery",
    totalDurationMinutes: 45,
    isActive: true,
    createdAt: "2024-02-01",
    updatedAt: "2024-04-01",
    exercises: [
      {
        id: "ex-008",
        name: "膝関節屈曲訓練",
        description: "TKA術後の膝屈曲可動域改善",
        category: "stretching",
        durationMinutes: 15,
        precautions: ["疼痛VAS 4以上は中止", "術後経過日数を確認"],
      },
      {
        id: "ex-009",
        name: "大腿四頭筋強化",
        description: "端座位での膝伸展運動",
        category: "strength",
        durationMinutes: 15,
        sets: 3,
        reps: 15,
      },
      {
        id: "ex-010",
        name: "歩行練習（歩行器）",
        description: "歩行器を使用した歩行訓練",
        category: "daily_activity",
        durationMinutes: 15,
      },
    ],
  },
  {
    id: "menu-004",
    name: "心臓疾患維持期 有酸素運動メニュー",
    diseaseType: "cardiac",
    phase: "maintenance",
    totalDurationMinutes: 40,
    isActive: true,
    createdAt: "2024-02-10",
    updatedAt: "2024-03-25",
    exercises: [
      {
        id: "ex-011",
        name: "ウォーミングアップ",
        description: "軽度の準備体操",
        category: "stretching",
        durationMinutes: 10,
      },
      {
        id: "ex-012",
        name: "トレッドミル歩行",
        description: "目標心拍数に合わせた歩行",
        category: "cardio",
        durationMinutes: 20,
        precautions: ["Borg指数13以下を維持", "胸痛・息切れ時は即中止"],
      },
      {
        id: "ex-013",
        name: "クールダウン",
        description: "整理体操・ストレッチ",
        category: "stretching",
        durationMinutes: 10,
      },
    ],
  },
  {
    id: "menu-005",
    name: "呼吸器疾患回復期 呼吸訓練メニュー",
    diseaseType: "respiratory",
    phase: "recovery",
    totalDurationMinutes: 35,
    isActive: true,
    createdAt: "2024-03-01",
    updatedAt: "2024-04-10",
    exercises: [
      {
        id: "ex-014",
        name: "腹式呼吸訓練",
        description: "横隔膜を使った呼吸法の習得",
        category: "daily_activity",
        durationMinutes: 10,
        reps: 10,
      },
      {
        id: "ex-015",
        name: "口すぼめ呼吸",
        description: "呼気を延長させる呼吸訓練",
        category: "daily_activity",
        durationMinutes: 10,
        reps: 10,
      },
      {
        id: "ex-016",
        name: "上肢体操",
        description: "呼吸と連動した上肢運動",
        category: "strength",
        durationMinutes: 15,
        sets: 2,
        reps: 10,
      },
    ],
  },
  {
    id: "menu-006",
    name: "ACL術後4ヶ月 スポーツ復帰準備メニュー",
    diseaseType: "orthopedic",
    phase: "recovery",
    totalDurationMinutes: 40,
    isActive: true,
    createdAt: "2026-04-01",
    updatedAt: "2026-05-10",
    exercises: [
      {
        id: "ex-017",
        name: "両脚スクワット",
        description: "膝がつま先より前に出ないよう体幹を安定させながら行う基本スクワット",
        category: "strength",
        durationMinutes: 10,
        sets: 3,
        reps: 15,
        precautions: ["膝前方に疼痛が出た場合は即中止", "深屈曲（90°以上）は避ける"],
      },
      {
        id: "ex-018",
        name: "片脚RDL（ルーマニアンデッドリフト）",
        description: "片脚立位で体幹を前傾させるハムストリングス強化＆動的バランス訓練",
        category: "balance",
        durationMinutes: 10,
        sets: 3,
        reps: 10,
        precautions: ["膝・股関節に痛みがある場合は中止", "転倒に十分注意する"],
      },
      {
        id: "ex-019",
        name: "ヒップリフト（ブリッジ）",
        description: "仰臥位で骨盤を持ち上げる臀筋・ハムストリングスの活性化訓練",
        category: "strength",
        durationMinutes: 8,
        sets: 3,
        reps: 15,
        precautions: ["腰痛がある場合は可動域を調整"],
      },
      {
        id: "ex-020",
        name: "ホッピング（両脚→片脚）",
        description: "両脚ホッピングから片脚ホッピングへ段階的に移行する動的動作訓練。スポーツ復帰に向けた着地衝撃への適応",
        category: "balance",
        durationMinutes: 12,
        sets: 3,
        reps: 20,
        precautions: [
          "膝の痛みや不安定感があれば即中止",
          "着地時は膝を軽く曲げて衝撃を吸収する",
          "術後4ヶ月以降・主治医許可後から開始",
        ],
      },
    ],
  },
];

export const patients: Patient[] = [
  {
    id: "pat-001",
    name: "田中 花子",
    age: 72,
    diseaseType: "stroke",
    currentPhase: "recovery",
    assignedMenuId: "menu-002",
    startDate: "2024-03-01",
    notes: "左片麻痺。高血圧の既往あり。",
    progress: [
      {
        date: "2024-04-10",
        menuId: "menu-002",
        completedExercises: ["ex-004", "ex-005", "ex-007"],
        durationMinutes: 45,
        painLevel: 2,
        fatigue: 3,
        notes: "歩行距離が伸びてきた",
      },
      {
        date: "2024-04-11",
        menuId: "menu-002",
        completedExercises: ["ex-004", "ex-005", "ex-006", "ex-007"],
        durationMinutes: 60,
        painLevel: 1,
        fatigue: 4,
      },
    ],
  },
  {
    id: "pat-002",
    name: "佐藤 一郎",
    age: 65,
    diseaseType: "orthopedic",
    currentPhase: "recovery",
    assignedMenuId: "menu-003",
    startDate: "2024-03-20",
    notes: "右TKA術後2週間。糖尿病管理中。",
    progress: [
      {
        date: "2024-04-10",
        menuId: "menu-003",
        completedExercises: ["ex-008", "ex-009"],
        durationMinutes: 30,
        painLevel: 4,
        fatigue: 5,
        notes: "疼痛強く歩行は短縮",
      },
    ],
  },
  {
    id: "pat-003",
    name: "山田 次郎",
    age: 58,
    diseaseType: "cardiac",
    currentPhase: "maintenance",
    assignedMenuId: "menu-004",
    startDate: "2024-01-15",
    notes: "心筋梗塞後3ヶ月。ペースメーカー未使用。",
    progress: [
      {
        date: "2024-04-10",
        menuId: "menu-004",
        completedExercises: ["ex-011", "ex-012", "ex-013"],
        durationMinutes: 40,
        painLevel: 0,
        fatigue: 2,
        notes: "Borg指数12で安定",
      },
    ],
  },
  {
    id: "pat-004",
    name: "鈴木 美代子",
    age: 68,
    diseaseType: "respiratory",
    currentPhase: "recovery",
    assignedMenuId: "menu-005",
    startDate: "2024-02-20",
    progress: [],
  },
  {
    id: "pat-005",
    name: "中村 健太",
    age: 24,
    diseaseType: "orthopedic",
    currentPhase: "recovery",
    assignedMenuId: "menu-006",
    startDate: "2026-04-01",
    notes: "右ACL再建術後4ヶ月。スポーツ（サッカー）復帰目標。",
    progress: [
      { date: "2026-04-01", menuId: "menu-006", completedExercises: ["ex-017", "ex-019"], durationMinutes: 20, painLevel: 6, fatigue: 7, notes: "術後初回。スクワット浅めで実施。" },
      { date: "2026-04-03", menuId: "menu-006", completedExercises: ["ex-017", "ex-019"], durationMinutes: 22, painLevel: 6, fatigue: 6 },
      { date: "2026-04-07", menuId: "menu-006", completedExercises: ["ex-017", "ex-018", "ex-019"], durationMinutes: 28, painLevel: 5, fatigue: 6, notes: "片脚RDL初導入。バランス不安定。" },
      { date: "2026-04-10", menuId: "menu-006", completedExercises: ["ex-017", "ex-018", "ex-019"], durationMinutes: 30, painLevel: 5, fatigue: 5 },
      { date: "2026-04-14", menuId: "menu-006", completedExercises: ["ex-017", "ex-018", "ex-019"], durationMinutes: 32, painLevel: 4, fatigue: 5, notes: "スクワット深度が改善。" },
      { date: "2026-04-17", menuId: "menu-006", completedExercises: ["ex-017", "ex-018", "ex-019"], durationMinutes: 33, painLevel: 4, fatigue: 4 },
      { date: "2026-04-21", menuId: "menu-006", completedExercises: ["ex-017", "ex-018", "ex-019"], durationMinutes: 35, painLevel: 3, fatigue: 4, notes: "ホッピング開始許可が下りた。" },
      { date: "2026-04-24", menuId: "menu-006", completedExercises: ["ex-017", "ex-018", "ex-019", "ex-020"], durationMinutes: 38, painLevel: 3, fatigue: 4, notes: "両脚ホッピング10回。着地安定。" },
      { date: "2026-04-28", menuId: "menu-006", completedExercises: ["ex-017", "ex-018", "ex-019", "ex-020"], durationMinutes: 40, painLevel: 3, fatigue: 3 },
      { date: "2026-05-01", menuId: "menu-006", completedExercises: ["ex-017", "ex-018", "ex-019", "ex-020"], durationMinutes: 40, painLevel: 2, fatigue: 3, notes: "片脚ホッピング開始。" },
      { date: "2026-05-05", menuId: "menu-006", completedExercises: ["ex-017", "ex-018", "ex-019", "ex-020"], durationMinutes: 40, painLevel: 2, fatigue: 2 },
      { date: "2026-05-08", menuId: "menu-006", completedExercises: ["ex-017", "ex-018", "ex-019", "ex-020"], durationMinutes: 40, painLevel: 1, fatigue: 2, notes: "フルメニュー完遂。膝の違和感なし。" },
      { date: "2026-05-12", menuId: "menu-006", completedExercises: ["ex-017", "ex-018", "ex-019", "ex-020"], durationMinutes: 40, painLevel: 1, fatigue: 1 },
    ],
  },
];

export const staffList: Staff[] = [
  { id: "staff-001", name: "木村 理学療法士", role: "physiotherapist" },
  { id: "staff-002", name: "伊藤 作業療法士", role: "occupational_therapist" },
  { id: "staff-003", name: "中村 看護師", role: "nurse" },
];
