// ──────────────────────────────────────────────
// リハビリ患者管理システム - サンプルデータ
// ──────────────────────────────────────────────
import type {
  Patient, Evaluation, Exercise, SOAPNote
} from '@/types/patient'

export const SAMPLE_PATIENTS: Patient[] = [
  {
    id: 'pt-001',
    name: '田中 太郎',
    kana: 'タナカ タロウ',
    birthDate: '1985-04-15',
    gender: 'male',
    phone: '090-1234-5678',
    emergencyContact: '田中 花子（妻）090-8765-4321',
    mainComplaint: '右膝の痛みと腫脹（半月板損傷術後）',
    bodyRegion: 'knee',
    diagnosisLabel: '右膝半月板部分切除術後',
    onsetDate: '2026-04-01',
    firstVisitDate: '2026-04-10',
    status: 'active',
    therapistNotes: '術後3週。主治医より荷重制限解除済み。段差・階段に不安あり。',
    createdAt: '2026-04-10T09:00:00',
    updatedAt: '2026-06-15T10:30:00',
  },
  {
    id: 'pt-002',
    name: '鈴木 美咲',
    kana: 'スズキ ミサキ',
    birthDate: '1998-11-22',
    gender: 'female',
    phone: '080-2345-6789',
    emergencyContact: '鈴木 一郎（父）080-9876-5432',
    mainComplaint: '右足関節捻挫後の痛みと不安定感',
    bodyRegion: 'ankle',
    diagnosisLabel: '右足関節外側靭帯損傷（保存療法）',
    onsetDate: '2026-05-20',
    firstVisitDate: '2026-05-22',
    status: 'active',
    therapistNotes: 'バスケットボール部。競技復帰希望。ATFL損傷。',
    createdAt: '2026-05-22T14:00:00',
    updatedAt: '2026-06-16T09:00:00',
  },
  {
    id: 'pt-003',
    name: '佐藤 健二',
    kana: 'サトウ ケンジ',
    birthDate: '1972-07-08',
    gender: 'male',
    phone: '070-3456-7890',
    emergencyContact: '佐藤 洋子（妻）070-0987-6543',
    mainComplaint: '腰痛・右下肢のしびれ',
    bodyRegion: 'lumbar',
    diagnosisLabel: '腰椎椎間板ヘルニア（保存療法）',
    onsetDate: '2026-03-15',
    firstVisitDate: '2026-03-20',
    status: 'active',
    therapistNotes: '建設業。重労働あり。SLR陽性（右）。',
    createdAt: '2026-03-20T11:00:00',
    updatedAt: '2026-06-10T15:00:00',
  },
  {
    id: 'pt-004',
    name: '山田 直子',
    kana: 'ヤマダ ナオコ',
    birthDate: '1955-01-30',
    gender: 'female',
    phone: '090-4567-8901',
    emergencyContact: '山田 誠（息子）090-1098-7654',
    mainComplaint: '右股関節の痛みと歩行困難',
    bodyRegion: 'hip',
    diagnosisLabel: '右変形性股関節症（保存療法）',
    onsetDate: '2025-10-01',
    firstVisitDate: '2025-10-15',
    status: 'active',
    therapistNotes: '68歳。階段・長距離歩行で痛み増強。Trendelenburg徴候あり。',
    createdAt: '2025-10-15T10:00:00',
    updatedAt: '2026-06-17T14:00:00',
  },
  {
    id: 'pt-005',
    name: '伊藤 大輔',
    kana: 'イトウ ダイスケ',
    birthDate: '2002-08-14',
    gender: 'male',
    phone: '080-5678-9012',
    emergencyContact: '伊藤 幸子（母）080-2109-8765',
    mainComplaint: '右肩の痛みと挙上困難',
    bodyRegion: 'shoulder',
    diagnosisLabel: '右肩腱板損傷（保存療法）',
    onsetDate: '2026-04-25',
    firstVisitDate: '2026-05-01',
    status: 'active',
    therapistNotes: '野球（投手）。投球時の痛み。棘上筋・棘下筋に圧痛あり。',
    createdAt: '2026-05-01T09:30:00',
    updatedAt: '2026-06-18T09:00:00',
  },
]

export const SAMPLE_EVALUATIONS: Evaluation[] = [
  {
    id: 'ev-001',
    patientId: 'pt-001',
    evaluationDate: '2026-04-10',
    painNrs: 6,
    restPain: false,
    nightPain: false,
    weightBearingPain: true,
    movementPain: true,
    swelling: true,
    heat: false,
    numbness: false,
    weakness: true,
    injuryMechanism: '右膝半月板部分切除術後3週',
    functionalLimitations: '階段昇降困難、長時間歩行困難',
    adlDifficulties: '階段、正座、しゃがみ動作',
    sportType: '',
    returnToSportDate: '',
    physicianConsult: true,
    imaging: true,
    contraindications: '深屈曲禁忌（主治医指示）',
    redFlags: {
      cauda_equina: false, fracture_risk: false, cancer: false,
      infection: false, vascular: false, severe_neuro: false, other: ''
    },
    therapistNotes: '術後3週。荷重OK。ROM屈曲110度まで。大腿四頭筋萎縮あり。',
    createdAt: '2026-04-10T09:30:00',
  },
  {
    id: 'ev-002',
    patientId: 'pt-002',
    evaluationDate: '2026-05-22',
    painNrs: 5,
    restPain: false,
    nightPain: false,
    weightBearingPain: true,
    movementPain: true,
    swelling: true,
    heat: true,
    numbness: false,
    weakness: false,
    injuryMechanism: 'バスケットボール試合中に着地時に捻挫',
    functionalLimitations: '走行困難、片脚立位不安定',
    adlDifficulties: '階段、走る、方向転換',
    sportType: 'バスケットボール',
    returnToSportDate: '2026-08-01',
    physicianConsult: false,
    imaging: false,
    contraindications: '',
    redFlags: {
      cauda_equina: false, fracture_risk: false, cancer: false,
      infection: false, vascular: false, severe_neuro: false, other: ''
    },
    therapistNotes: 'ATFL圧痛強い。Anterior Drawer test陽性。軽度腫脹あり。',
    createdAt: '2026-05-22T14:30:00',
  },
]

export const SAMPLE_SOAP_NOTES: SOAPNote[] = [
  {
    id: 'soap-001',
    patientId: 'pt-001',
    visitDate: '2026-06-10',
    visitNumber: 15,
    painToday: 3,
    changeFromLast: '階段が少し楽になった気がする',
    adlDifficulty: '長時間歩行はまだ少し痛む',
    homeExerciseAdherence: 'done',
    patientConcern: 'いつ完全に痛みがとれるか不安',
    patientGoalToday: '階段をもっと楽に降りたい',
    romFindings: '膝屈曲：右125度（前回115度）',
    strengthFindings: '大腿四頭筋MMT：右4',
    specialTestFindings: 'McMurray陰性',
    tenderness: '関節裂隙圧痛残存（軽度）',
    swelling: false,
    heat: false,
    gait: '軽度右膝伸展制限あり',
    singleLegStance: '右10秒',
    squat: '深屈曲は制限あり',
    therapistObservation: '階段降段時の膝制動力改善傾向',
    improvements: 'ROM改善、腫脹消退、痛みNRS減少',
    remainingIssues: '大腿四頭筋筋力、深屈曲制限',
    priorityIssue: '筋力強化と動的安定性',
    currentPhase: 3,
    visitFrequencyAppropriate: true,
    exerciseLoadAppropriate: true,
    physicianReferralNeeded: false,
    treatmentToday: '膝周囲ストレッチ、スクワット練習、階段降段練習',
    nextGoal: '片脚スクワット安定、階段降段の痛み軽減',
    homeExercise: 'スクワット15回×3セット、カーフレイズ20回×3セット',
    forbiddenMovements: '深屈曲（130度以上）',
    recommendedFrequency: '週2回',
    nextReassessment: '2026-07-10（3ヶ月再評価）',
    createdAt: '2026-06-10T11:00:00',
  },
]

export const SAMPLE_EXERCISES: Exercise[] = [
  {
    id: 'ex-001',
    name: '足関節ポンプ運動',
    bodyRegion: 'ankle',
    purpose: '血流促進・浮腫軽減・静脈血栓予防',
    phase: [1, 2],
    difficulty: 'easy',
    contraindications: '特になし',
    reps: '20回',
    sets: 3,
    frequency: '1日2〜3回',
    patientInstruction: '足首を上下にゆっくり動かしましょう。痛みが出ない範囲で行ってください。むくみが気になるときに特に効果的です。',
    therapistNote: '臥位または座位で実施。術後早期から可。',
    progressionCriteria: '痛みなく20回できたらカーフレイズへ',
    regressionCriteria: '痛みが増す場合は回数を減らす',
    svgIllustration: 'pump',
    createdAt: '2026-01-01T00:00:00',
  },
  {
    id: 'ex-002',
    name: 'クラムシェル',
    bodyRegion: 'hip',
    purpose: '股関節外旋・外転筋（中殿筋・深層外旋筋群）の強化',
    phase: [2, 3],
    difficulty: 'easy',
    contraindications: '股関節唇損傷：角度注意',
    reps: '15回',
    sets: 3,
    frequency: '1日1回',
    patientInstruction: '横向きに寝て、膝を曲げた状態でゆっくり上の足を開きましょう。お尻の外側が使えている感覚を確認しながら行ってください。',
    therapistNote: '側臥位。骨盤を固定して腰が回らないように注意。',
    progressionCriteria: '15回×3セット安定後、チューブ抵抗追加',
    regressionCriteria: '股関節に痛みが出る場合は中止',
    svgIllustration: 'clamshell',
    createdAt: '2026-01-01T00:00:00',
  },
  {
    id: 'ex-003',
    name: 'ブリッジ',
    bodyRegion: 'hip',
    purpose: '殿筋・ハムストリングス・体幹後面の強化',
    phase: [2, 3, 4],
    difficulty: 'easy',
    contraindications: '腰部に痛みが増す場合は中止',
    reps: '15回',
    sets: 3,
    frequency: '1日1回',
    patientInstruction: '仰向けで膝を曲げた状態でお尻を持ち上げましょう。お尻から背中にかけての筋肉を意識してください。腰を反りすぎないように注意しましょう。',
    therapistNote: '骨盤を水平に保つ。腹横筋収縮させてから挙上。',
    progressionCriteria: '片脚ブリッジへ段階的に移行',
    regressionCriteria: '腰痛が増す場合は実施角度を調整',
    svgIllustration: 'bridge',
    createdAt: '2026-01-01T00:00:00',
  },
  {
    id: 'ex-004',
    name: '片脚立位',
    bodyRegion: 'knee',
    purpose: 'バランス・固有感覚・動的安定性の向上',
    phase: [3, 4, 5],
    difficulty: 'medium',
    contraindications: '荷重痛が強い場合・術後荷重制限中は禁忌',
    reps: '30秒×3セット',
    sets: 3,
    frequency: '1日1〜2回',
    patientInstruction: '片脚でまっすぐ立ってみましょう。はじめは壁の近くで行って、安定してきたら壁から離れてください。30秒間バランスをとることを目標にしましょう。',
    therapistNote: '支持脚膝軽度屈曲位で。骨盤水平保持を確認。',
    progressionCriteria: '平地30秒安定後、不安定板・目閉じ',
    regressionCriteria: '膝に痛みが出る場合は実施を中断',
    svgIllustration: 'single_leg',
    createdAt: '2026-01-01T00:00:00',
  },
  {
    id: 'ex-005',
    name: 'カーフレイズ',
    bodyRegion: 'ankle',
    purpose: '下腿三頭筋強化・立脚安定性向上',
    phase: [2, 3, 4],
    difficulty: 'medium',
    contraindications: '跟骨骨折・術後荷重制限',
    reps: '20回',
    sets: 3,
    frequency: '1日1回',
    patientInstruction: '立った状態でゆっくりつま先立ちをしましょう。ふくらはぎが使えている感覚を確認してください。痛みが出ない範囲で行いましょう。',
    therapistNote: '最初は両脚で。安定後に患側片脚へ。',
    progressionCriteria: '両脚20回→片脚10回以上で次段階',
    regressionCriteria: '足関節に痛みが増す場合は中止',
    svgIllustration: 'calf_raise',
    createdAt: '2026-01-01T00:00:00',
  },
  {
    id: 'ex-006',
    name: '肩甲骨セッティング',
    bodyRegion: 'shoulder',
    purpose: '肩甲骨安定筋群の賦活・肩関節アライメント改善',
    phase: [1, 2, 3],
    difficulty: 'easy',
    contraindications: '特になし',
    reps: '10秒保持×10回',
    sets: 3,
    frequency: '1日2回',
    patientInstruction: '肩甲骨を少しだけ後ろに引き寄せ、軽く下に動かしましょう。肩の力を抜いたまま、背中の中央あたりを意識してください。',
    therapistNote: '「後ろ・下」方向への肩甲骨運動。僧帽筋下部・菱形筋の賦活。',
    progressionCriteria: '座位→立位→機能的動作へ',
    regressionCriteria: '肩に痛みが増す場合は実施中断',
    svgIllustration: 'scapular',
    createdAt: '2026-01-01T00:00:00',
  },
  {
    id: 'ex-007',
    name: '体幹ブレーシング',
    bodyRegion: 'lumbar',
    purpose: '体幹安定筋群の賦活・腰部負荷軽減',
    phase: [1, 2, 3, 4],
    difficulty: 'easy',
    contraindications: '特になし',
    reps: '10秒保持×10回',
    sets: 3,
    frequency: '1日2回',
    patientInstruction: 'お腹を軽くへこませながら力を入れてください（コルセットを締めるイメージ）。息は止めずに自然に呼吸しながら行いましょう。',
    therapistNote: '腹横筋優位の収縮。腹圧を上げる意識。',
    progressionCriteria: '静止位→動作中（歩行・スクワット）への応用',
    regressionCriteria: '腰痛が増す場合は姿勢を調整',
    svgIllustration: 'bracing',
    createdAt: '2026-01-01T00:00:00',
  },
  {
    id: 'ex-008',
    name: 'チューブ外旋',
    bodyRegion: 'shoulder',
    purpose: '外旋筋群（棘下筋・小円筋）の強化・投球障害予防',
    phase: [3, 4, 5],
    difficulty: 'medium',
    contraindications: '急性期の痛みが強い場合は禁忌',
    reps: '15回',
    sets: 3,
    frequency: '1日1回',
    patientInstruction: '肘を体に軽くつけた状態で、チューブをつかんで外側に回しましょう。肩の後ろ側が使えている感覚を確認してください。',
    therapistNote: '第1肢位での外旋。肘90度屈曲。体幹の回旋を防ぐ。',
    progressionCriteria: '第1肢位→第2肢位（外転90度位）へ',
    regressionCriteria: '肩の痛みが増す場合は荷重を下げる',
    svgIllustration: 'tube_er',
    createdAt: '2026-01-01T00:00:00',
  },
  {
    id: 'ex-009',
    name: 'スクワット',
    bodyRegion: 'knee',
    purpose: '大腿四頭筋・殿筋・下肢全体の筋力強化',
    phase: [3, 4, 5],
    difficulty: 'medium',
    contraindications: '荷重痛が強い場合・深屈曲禁忌がある場合は角度制限',
    reps: '15回',
    sets: 3,
    frequency: '1日1回',
    patientInstruction: '足を肩幅に開いて、ゆっくり椅子に腰をかけるように膝を曲げましょう。膝がつま先より前に出すぎないよう注意してください。痛みが出ない範囲で行いましょう。',
    therapistNote: '膝前額面のアライメント確認。軟骨病変がある場合は角度制限。',
    progressionCriteria: '両脚→片脚スクワット。負荷漸増。',
    regressionCriteria: '膝に痛みが増す場合は可動域を制限',
    svgIllustration: 'squat',
    createdAt: '2026-01-01T00:00:00',
  },
  {
    id: 'ex-010',
    name: '呼吸エクササイズ',
    bodyRegion: 'lumbar',
    purpose: '横隔膜機能改善・体幹安定化・リラクゼーション',
    phase: [1, 2, 3, 4, 5, 6],
    difficulty: 'easy',
    contraindications: '特になし',
    reps: '5回',
    sets: 3,
    frequency: '1日2〜3回',
    patientInstruction: '仰向けでお腹に手を当て、鼻からゆっくり息を吸ってお腹を膨らませましょう。口からゆっくり吐いてお腹をへこませてください。',
    therapistNote: '横隔膜呼吸（腹式呼吸）。腹圧・体幹安定化に繋げる導入として。',
    progressionCriteria: '座位・立位でも安定して実施できるよう',
    regressionCriteria: '特になし',
    svgIllustration: 'breathing',
    createdAt: '2026-01-01T00:00:00',
  },
]
