import type { User, RehabCase, VideoComment, EvaluationResult } from '@/types/rehab'

export const MOCK_USERS: User[] = [
  {
    id: 'user-001',
    name: '鈴木 花子',
    role: 'admin',
    department: 'リハビリテーション科',
    email: 'suzuki@rehab.example.com',
  },
  {
    id: 'user-002',
    name: '田中 一郎',
    role: 'doctor',
    department: '整形外科',
    email: 'tanaka@rehab.example.com',
  },
  {
    id: 'user-003',
    name: '佐藤 真也',
    role: 'trainer',
    department: 'スポーツリハビリ',
    email: 'sato@rehab.example.com',
  },
  {
    id: 'user-004',
    name: '山田 美咲',
    role: 'pt',
    department: 'リハビリテーション科',
    email: 'yamada@rehab.example.com',
  },
  // ダンス専門家
  {
    id: 'user-005',
    name: '白川 優奈',
    role: 'ballet_coach',
    department: 'バレエ・クラシックダンス部門',
    email: 'shirakawa@dance.example.com',
  },
  {
    id: 'user-006',
    name: '木村 隆二',
    role: 'jazz_coach',
    department: 'ジャズ・コンテンポラリー部門',
    email: 'kimura@dance.example.com',
  },
  {
    id: 'user-007',
    name: 'DJ Yoshi（吉田 康介）',
    role: 'hiphop_coach',
    department: 'ストリートダンス部門',
    email: 'yoshi@dance.example.com',
  },
  {
    id: 'user-008',
    name: 'B-boy Ryu（龍崎 雄太）',
    role: 'breakdance_coach',
    department: 'ブレイキン部門',
    email: 'ryu@dance.example.com',
  },
]


export const MOCK_CASES: RehabCase[] = [
  {
    id: 'case-001',
    anonymousId: 'PT-2026-001',
    patientName: '山本 健太',
    age: 22,
    gender: 'male',
    diagnosis: '右ACL再建術後',
    injuredPart: '右膝関節',
    postOpDays: 120,
    evaluationPurpose: 'スポーツ復帰前機能評価（ジャンプ着地・方向転換）',
    status: 'preReturn',
    assignedTo: ['user-001', 'user-003'],
    reviewers: ['user-002'],
    tags: ['ACL', '術後', 'スポーツ復帰', 'ジャンプ', '膝関節'],
    createdAt: '2026-01-15T09:00:00',
    updatedAt: '2026-05-15T14:30:00',
    videos: [
      {
        id: 'video-001-1',
        caseId: 'case-001',
        label: '両脚スクワット（正面）',
        direction: 'front',
        movementType: 'squat',
        tags: ['スクワット', '正面'],
        uploadedAt: '2026-05-15T10:00:00',
        uploadedBy: 'user-001',
        fileName: 'squat_front.mp4',
        duration: 15,
      },
      {
        id: 'video-001-2',
        caseId: 'case-001',
        label: '片脚ジャンプ着地（側面）',
        direction: 'side',
        movementType: 'jump',
        tags: ['ジャンプ', '着地', '側面'],
        uploadedAt: '2026-05-15T10:05:00',
        uploadedBy: 'user-001',
        fileName: 'jump_side.mp4',
        duration: 10,
      },
    ],
  },
  {
    id: 'case-002',
    anonymousId: 'PT-2026-002',
    age: 68,
    gender: 'female',
    diagnosis: '両側変形性膝関節症',
    injuredPart: '両膝関節',
    evaluationPurpose: '歩行能力評価・疼痛パターン確認',
    status: 'intervention',
    assignedTo: ['user-001', 'user-004'],
    reviewers: ['user-002'],
    tags: ['変形性膝関節症', '歩行', '高齢者', '疼痛'],
    createdAt: '2026-02-10T09:00:00',
    updatedAt: '2026-05-10T11:00:00',
    videos: [
      {
        id: 'video-002-1',
        caseId: 'case-002',
        label: '10m歩行テスト（側面）',
        direction: 'side',
        movementType: 'walking',
        tags: ['歩行', '10mテスト', '側面'],
        uploadedAt: '2026-05-10T09:30:00',
        uploadedBy: 'user-004',
        fileName: 'walk_side.mp4',
        duration: 25,
      },
      {
        id: 'video-002-2',
        caseId: 'case-002',
        label: '10m歩行テスト（後方）',
        direction: 'rear',
        movementType: 'walking',
        tags: ['歩行', '10mテスト', '後方'],
        uploadedAt: '2026-05-10T09:35:00',
        uploadedBy: 'user-004',
        fileName: 'walk_rear.mp4',
        duration: 25,
      },
    ],
  },
  {
    id: 'case-003',
    anonymousId: 'PT-2026-003',
    age: 35,
    gender: 'male',
    diagnosis: '右肩腱板断裂術後',
    injuredPart: '右肩関節',
    postOpDays: 60,
    evaluationPurpose: '肩関節可動域・肩甲骨運動評価',
    status: 'intervention',
    assignedTo: ['user-001'],
    reviewers: ['user-002', 'user-003'],
    tags: ['肩腱板', '術後', '肩関節', '肩甲骨'],
    createdAt: '2026-03-20T09:00:00',
    updatedAt: '2026-05-18T16:00:00',
    videos: [
      {
        id: 'video-003-1',
        caseId: 'case-003',
        label: '肩関節屈曲・外転（正面）',
        direction: 'front',
        movementType: 'shoulder',
        tags: ['肩関節', '屈曲', '外転', '正面'],
        uploadedAt: '2026-05-18T14:00:00',
        uploadedBy: 'user-001',
        fileName: 'shoulder_front.mp4',
        duration: 20,
      },
    ],
  },
  {
    id: 'case-004',
    anonymousId: 'PT-2026-004',
    age: 58,
    gender: 'male',
    diagnosis: '脳梗塞後右片麻痺',
    injuredPart: '右上下肢',
    evaluationPurpose: '歩行パターン・立ち上がり動作評価',
    status: 'intervention',
    assignedTo: ['user-004'],
    reviewers: ['user-001', 'user-002'],
    tags: ['脳梗塞', '片麻痺', '歩行', '立ち上がり', '神経疾患'],
    createdAt: '2026-04-01T09:00:00',
    updatedAt: '2026-05-16T10:00:00',
    videos: [
      {
        id: 'video-004-1',
        caseId: 'case-004',
        label: '歩行（正面）',
        direction: 'front',
        movementType: 'walking',
        tags: ['歩行', '正面', '片麻痺'],
        uploadedAt: '2026-05-16T09:00:00',
        uploadedBy: 'user-004',
        fileName: 'gait_front.mp4',
        duration: 30,
      },
      {
        id: 'video-004-2',
        caseId: 'case-004',
        label: '椅子からの立ち上がり（側面）',
        direction: 'side',
        movementType: 'sitsToStand',
        tags: ['立ち上がり', '側面'],
        uploadedAt: '2026-05-16T09:10:00',
        uploadedBy: 'user-004',
        fileName: 'sit_to_stand.mp4',
        duration: 15,
      },
    ],
  },
  {
    id: 'case-005',
    anonymousId: 'PT-2026-005',
    patientName: '中村 さくら',
    age: 19,
    gender: 'female',
    diagnosis: '右足関節外側靱帯損傷（ATFL断裂）',
    injuredPart: '右足関節',
    postOpDays: 21,
    evaluationPurpose: 'ジャンプ着地・方向転換時の足関節安定性評価',
    status: 'initial',
    assignedTo: ['user-003'],
    reviewers: ['user-001'],
    tags: ['足関節', '靱帯損傷', 'ジャンプ', '着地', 'スポーツ'],
    createdAt: '2026-05-01T09:00:00',
    updatedAt: '2026-05-19T09:00:00',
    videos: [],
  },
  // ダンス競技症例
  {
    id: 'case-006',
    anonymousId: 'DANCE-2026-001',
    patientName: '橘 凛（仮名）',
    age: 17,
    gender: 'female',
    diagnosis: '両側腸腰筋炎・左膝前十字靱帯不全損傷疑い',
    injuredPart: '左膝関節・両側股関節',
    postOpDays: undefined,
    evaluationPurpose: 'ダンス競技復帰前の多専門家評価（バレエ・ジャズ・Hip hop・ブレイキン各コーチによる動作確認）',
    status: 'preReturn',
    assignedTo: ['user-001', 'user-005', 'user-006'],
    reviewers: ['user-002', 'user-007', 'user-008'],
    tags: ['ダンス', 'バレエ', 'ジャズ', 'Hip hop', 'ブレイキン', '膝関節', '股関節', '競技復帰'],
    createdAt: '2026-04-20T09:00:00',
    updatedAt: '2026-05-19T18:00:00',
    videos: [
      {
        id: 'video-006-1',
        caseId: 'case-006',
        label: 'バレエ：プリエ・ルルヴェ（正面）',
        direction: 'front',
        movementType: 'ballet',
        tags: ['バレエ', 'プリエ', 'ルルヴェ', '正面'],
        uploadedAt: '2026-05-18T10:00:00',
        uploadedBy: 'user-001',
        fileName: 'ballet_plie_front.mp4',
        duration: 20,
      },
      {
        id: 'video-006-2',
        caseId: 'case-006',
        label: 'ブレイキン：フリーズ・チェア（側面）',
        direction: 'side',
        movementType: 'breakdance',
        tags: ['ブレイキン', 'フリーズ', 'チェア', '側面'],
        uploadedAt: '2026-05-18T10:20:00',
        uploadedBy: 'user-008',
        fileName: 'bboy_freeze_side.mp4',
        duration: 15,
      },
      {
        id: 'video-006-3',
        caseId: 'case-006',
        label: 'Hip hop：グルーブ・バウンス（正面）',
        direction: 'front',
        movementType: 'hiphop',
        tags: ['Hip hop', 'グルーブ', 'バウンス', '正面'],
        uploadedAt: '2026-05-18T10:35:00',
        uploadedBy: 'user-007',
        fileName: 'hiphop_groove_front.mp4',
        duration: 18,
      },
      {
        id: 'video-006-4',
        caseId: 'case-006',
        label: 'ジャズ：コンビネーション（側面）',
        direction: 'side',
        movementType: 'jazz',
        tags: ['ジャズ', 'コンビネーション', '側面'],
        uploadedAt: '2026-05-18T10:50:00',
        uploadedBy: 'user-006',
        fileName: 'jazz_combo_side.mp4',
        duration: 22,
      },
    ],
  },
]

export const MOCK_COMMENTS: VideoComment[] = [
  {
    id: 'comment-001',
    videoId: 'video-001-1',
    caseId: 'case-001',
    timestamp: 3.2,
    text: '右膝のニーインが顕著。大腿四頭筋の筋力低下と考えられる。VMOの選択的トレーニングが必要。',
    type: 'problem',
    authorId: 'user-001',
    authorName: '鈴木 花子',
    authorRole: 'pt',
    createdAt: '2026-05-15T11:00:00',
    replies: [
      {
        id: 'reply-001',
        commentId: 'comment-001',
        text: '同意します。股関節外転筋群の強化も合わせて行うべきと思います。',
        authorId: 'user-003',
        authorName: '佐藤 真也',
        createdAt: '2026-05-15T14:00:00',
      },
    ],
    reactions: [
      { type: 'agree', userId: 'user-003', userName: '佐藤 真也' },
      { type: 'important', userId: 'user-002', userName: '田中 一郎' },
    ],
  },
  {
    id: 'comment-002',
    videoId: 'video-001-1',
    caseId: 'case-001',
    timestamp: 7.5,
    text: '体幹の前傾は良好。バランスも安定している。',
    type: 'positive',
    authorId: 'user-001',
    authorName: '鈴木 花子',
    authorRole: 'pt',
    createdAt: '2026-05-15T11:05:00',
    replies: [],
    reactions: [{ type: 'agree', userId: 'user-004', userName: '山田 美咲' }],
  },
  {
    id: 'comment-003',
    videoId: 'video-001-2',
    caseId: 'case-001',
    timestamp: 2.0,
    text: '着地時に膝外反が見られる。ACL再損傷リスクあり。スポーツ復帰の判断は慎重に行う必要がある可能性があります。専門家による追加評価を推奨。',
    type: 'risk',
    authorId: 'user-002',
    authorName: '田中 一郎',
    authorRole: 'doctor',
    createdAt: '2026-05-16T10:00:00',
    replies: [],
    reactions: [
      { type: 'important', userId: 'user-001', userName: '鈴木 花子' },
      { type: 'review', userId: 'user-003', userName: '佐藤 真也' },
    ],
  },
  {
    id: 'comment-004',
    videoId: 'video-002-1',
    caseId: 'case-002',
    timestamp: 5.0,
    text: '右立脚期に軽度のトレンデレンブルグ徴候を認める。中殿筋の筋力低下が疑われる。',
    type: 'problem',
    authorId: 'user-004',
    authorName: '山田 美咲',
    authorRole: 'pt',
    createdAt: '2026-05-10T10:00:00',
    replies: [],
    reactions: [{ type: 'agree', userId: 'user-001', userName: '鈴木 花子' }],
  },
  // ACL再建術後（video-001-1）追加コメント
  {
    id: 'comment-019',
    videoId: 'video-001-1',
    caseId: 'case-001',
    timestamp: 5.8,
    text: '着地時の膝外反が顕著で、ACL再損傷リスクが高い状態です。スポーツ復帰の最終判断前に徒手検査とKT-1000による客観的評価を追加することを推奨します。',
    type: 'risk',
    authorId: 'user-002',
    authorName: '田中 一郎',
    authorRole: 'doctor',
    createdAt: '2026-05-15T13:00:00',
    replies: [],
    reactions: [
      { type: 'important', userId: 'user-001', userName: '鈴木 花子' },
      { type: 'important', userId: 'user-004', userName: '山田 美咲' },
    ],
  },
  {
    id: 'comment-020',
    videoId: 'video-001-1',
    caseId: 'case-001',
    timestamp: 9.2,
    text: '体幹筋力強化プログラムの導入を推奨します。特にプランクバリエーションと臀部ブリッジを週3回以上。着地動作の改善には股関節外転筋群・ハムストリングスの協調収縮トレーニングが有効です。',
    type: 'improvement',
    authorId: 'user-003',
    authorName: '佐藤 真也',
    authorRole: 'trainer',
    createdAt: '2026-05-15T15:30:00',
    replies: [
      {
        id: 'reply-020-1',
        commentId: 'comment-020',
        text: '同意します。シングルレッグスクワットで荷重時のニーイン改善を確認してからジャンプ系に移行しましょう。',
        authorId: 'user-004',
        authorName: '山田 美咲',
        createdAt: '2026-05-15T16:00:00',
      },
    ],
    reactions: [
      { type: 'agree', userId: 'user-001', userName: '鈴木 花子' },
      { type: 'agree', userId: 'user-004', userName: '山田 美咲' },
    ],
  },
  {
    id: 'comment-021',
    videoId: 'video-001-1',
    caseId: 'case-001',
    timestamp: 12.0,
    text: '術後8ヶ月の評価として、膝の安定性は改善傾向にあります。ただし右立脚中期に軽度の外側体重移動が残存。インソール調整と足部アーチトレーニングを継続してください。',
    type: 'problem',
    authorId: 'user-004',
    authorName: '山田 美咲',
    authorRole: 'pt',
    createdAt: '2026-05-16T09:00:00',
    replies: [],
    reactions: [
      { type: 'agree', userId: 'user-003', userName: '佐藤 真也' },
      { type: 'review', userId: 'user-002', userName: '田中 一郎' },
    ],
  },
  // ダンス症例コメント（video-006-1：バレエ プリエ・ルルヴェ）
  {
    id: 'comment-010',
    videoId: 'video-006-1',
    caseId: 'case-006',
    timestamp: 3.5,
    text: '左プリエ時に膝の内側偏位（ニーイン）が見られます。ターンアウトの強制による腸脛靱帯・膝関節への負荷が懸念されます。現時点では競技復帰は段階的に行うべきです。',
    type: 'risk',
    authorId: 'user-005',
    authorName: '白川 優奈',
    authorRole: 'ballet_coach',
    createdAt: '2026-05-18T11:00:00',
    replies: [
      {
        id: 'reply-010-1',
        commentId: 'comment-010',
        text: '腸腰筋炎の既往も踏まえると、フルターンアウトは当面制限が必要だと思います。',
        authorId: 'user-001',
        authorName: '鈴木 花子',
        createdAt: '2026-05-18T14:00:00',
      },
    ],
    reactions: [
      { type: 'agree', userId: 'user-001', userName: '鈴木 花子' },
      { type: 'important', userId: 'user-002', userName: '田中 一郎' },
    ],
  },
  {
    id: 'comment-011',
    videoId: 'video-006-1',
    caseId: 'case-006',
    timestamp: 8.0,
    text: 'ルルヴェの高さは左右差がほぼなく良好。ただし着地時のエネルギー吸収が不十分で膝が硬直気味。バレエ特有の「静かな着地」のキューイングを継続してください。',
    type: 'improvement',
    authorId: 'user-005',
    authorName: '白川 優奈',
    authorRole: 'ballet_coach',
    createdAt: '2026-05-18T11:10:00',
    replies: [],
    reactions: [{ type: 'agree', userId: 'user-006', userName: '木村 隆二' }],
  },
  {
    id: 'comment-012',
    videoId: 'video-006-1',
    caseId: 'case-006',
    timestamp: 5.2,
    text: 'ジャズの視点から：股関節の外旋可動域は競技水準に達しているが、体幹の側屈制御が弱い。バレエとジャズ共通の課題として脊柱安定筋のトレーニングが有効です。',
    type: 'suggestion',
    authorId: 'user-006',
    authorName: '木村 隆二',
    authorRole: 'jazz_coach',
    createdAt: '2026-05-18T12:30:00',
    replies: [],
    reactions: [{ type: 'agree', userId: 'user-005', userName: '白川 優奈' }],
  },
  {
    id: 'comment-013',
    videoId: 'video-006-1',
    caseId: 'case-006',
    timestamp: 10.0,
    text: '整形外科的所見：左膝前外側の不安定性が動画からも読み取れます。ACL不全損傷の疑いがあり、MRI・徒手検査による精密評価を先行させることを強く推奨します。競技復帰判断はその結果を待ってから。',
    type: 'risk',
    authorId: 'user-002',
    authorName: '田中 一郎',
    authorRole: 'doctor',
    createdAt: '2026-05-18T15:00:00',
    replies: [],
    reactions: [
      { type: 'important', userId: 'user-001', userName: '鈴木 花子' },
      { type: 'important', userId: 'user-005', userName: '白川 優奈' },
      { type: 'review', userId: 'user-006', userName: '木村 隆二' },
    ],
  },
  // ダンス症例コメント（video-006-2：ブレイキン）
  {
    id: 'comment-014',
    videoId: 'video-006-2',
    caseId: 'case-006',
    timestamp: 4.0,
    text: 'チェアのフリーズで右手首に過度な背屈が見られます。TFCC（三角線維軟骨複合体）への繰り返しストレスが危惧される。手首サポーターの着用と、荷重分散テクニックの指導が必要です。',
    type: 'risk',
    authorId: 'user-008',
    authorName: 'B-boy Ryu（龍崎 雄太）',
    authorRole: 'breakdance_coach',
    createdAt: '2026-05-18T13:00:00',
    replies: [
      {
        id: 'reply-014-1',
        commentId: 'comment-014',
        text: '整形外科的にも同意見です。右手根関節の評価も追加してください。',
        authorId: 'user-002',
        authorName: '田中 一郎',
        createdAt: '2026-05-18T15:10:00',
      },
    ],
    reactions: [
      { type: 'agree', userId: 'user-001', userName: '鈴木 花子' },
      { type: 'important', userId: 'user-002', userName: '田中 一郎' },
    ],
  },
  {
    id: 'comment-015',
    videoId: 'video-006-2',
    caseId: 'case-006',
    timestamp: 9.0,
    text: '体幹の安定性・コアストレングスは申し分ない。フリーズの保持時間も規定を満たしています。膝の問題が解決されれば、ブレイキン競技のヘッドスピン系以外は許可できると判断します。',
    type: 'positive',
    authorId: 'user-008',
    authorName: 'B-boy Ryu（龍崎 雄太）',
    authorRole: 'breakdance_coach',
    createdAt: '2026-05-18T13:15:00',
    replies: [],
    reactions: [{ type: 'agree', userId: 'user-007', userName: 'DJ Yoshi（吉田 康介）' }],
  },
  // ダンス症例コメント（video-006-3：Hip hop）
  {
    id: 'comment-016',
    videoId: 'video-006-3',
    caseId: 'case-006',
    timestamp: 5.5,
    text: 'バウンス時の膝の屈伸リズムは良好。ただしグルーブのダウンムーブメントで左膝が内側に入る癖があります。Hip hopにおける繰り返し動作なので、長期的な軟骨への影響を注視してください。',
    type: 'problem',
    authorId: 'user-007',
    authorName: 'DJ Yoshi（吉田 康介）',
    authorRole: 'hiphop_coach',
    createdAt: '2026-05-18T14:00:00',
    replies: [],
    reactions: [
      { type: 'agree', userId: 'user-005', userName: '白川 優奈' },
      { type: 'review', userId: 'user-001', userName: '鈴木 花子' },
    ],
  },
  {
    id: 'comment-017',
    videoId: 'video-006-3',
    caseId: 'case-006',
    timestamp: 12.0,
    text: 'フットワーク・ステップの切れは競技レベルに達している。上半身のアームコントロールも安定しており、Hip hop単独での復帰許可を支持します。ただし医師・PTの最終承認が前提です。',
    type: 'positive',
    authorId: 'user-007',
    authorName: 'DJ Yoshi（吉田 康介）',
    authorRole: 'hiphop_coach',
    createdAt: '2026-05-18T14:20:00',
    replies: [],
    reactions: [{ type: 'agree', userId: 'user-008', userName: 'B-boy Ryu（龍崎 雄太）' }],
  },
  // ダンス症例コメント（video-006-4：ジャズ）
  {
    id: 'comment-018',
    videoId: 'video-006-4',
    caseId: 'case-006',
    timestamp: 7.0,
    text: 'ジャズのコンビネーションで体幹回旋は良好。スプリットへの移行も左右差が少ない。ただしキック系の動作で左膝の過伸展傾向があり、ハムストリングスの遠心性筋力強化を追加指示したいです。',
    type: 'improvement',
    authorId: 'user-006',
    authorName: '木村 隆二',
    authorRole: 'jazz_coach',
    createdAt: '2026-05-18T15:30:00',
    replies: [
      {
        id: 'reply-018-1',
        commentId: 'comment-018',
        text: 'ハムストリングスの遠心性トレーニングはNordic hamstringからプログラムを組みます。',
        authorId: 'user-001',
        authorName: '鈴木 花子',
        createdAt: '2026-05-18T16:00:00',
      },
    ],
    reactions: [{ type: 'agree', userId: 'user-001', userName: '鈴木 花子' }],
  },
]

export const MOCK_EVALUATIONS: EvaluationResult[] = [
  {
    id: 'eval-001',
    caseId: 'case-001',
    videoId: 'video-001-1',
    movementType: 'squat',
    items: [
      { key: 'trunk_lean', label: '体幹前傾', severity: 'none', checked: false, note: '' },
      { key: 'pelvis_tilt', label: '骨盤後傾', severity: 'mild', checked: true, note: '軽度の後傾あり' },
      { key: 'knee_valgus', label: '膝の内側偏位（ニーイン）', severity: 'moderate', checked: true, note: '右膝に顕著' },
      { key: 'foot_arch', label: '足部アーチ低下', severity: 'mild', checked: true, note: '両側軽度' },
      { key: 'weight_shift', label: '左右荷重差', severity: 'mild', checked: true, note: '右に5%程度の荷重増加' },
      { key: 'depth', label: '深度（しゃがみ込み深さ）', severity: 'none', checked: false, note: '' },
      { key: 'heel_rise', label: 'かかとの浮き上がり', severity: 'none', checked: false, note: '' },
    ],
    overallNote: '右膝のニーインが最も顕著な問題点。VMO・股関節外転筋群の強化が優先課題。',
    evaluatedBy: 'user-001',
    evaluatedByName: '鈴木 花子',
    evaluatedAt: '2026-05-15T12:00:00',
  },
]
